---
title: 'A comparison of Fractional polynomials, meta-STEPP and smoothing splines to investigate effect modification in IPD-MA : a simulation study'
author: "Michail Belias"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
  - \usepackage{bbm}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{dsfont}
  - \usepackage{multirow}
  - \usepackage{wrapfig}
  - \usepackage{float}
  - \usepackage{colortbl}
  - \usepackage{pdflscape}
  - \usepackage{tabu}
  - \usepackage{threeparttable}
  - \usepackage{threeparttablex}
  - \usepackage[normalem]{ulem}
  - \usepackage{makecell}
  - \newcommand{\blandscape}{\begin{landscape}}
  - \newcommand{\elandscape}{\end{landscape}}
  - \DeclareUnicodeCharacter{2212}{-}
output:
 pdf_document:
    fig_caption: yes
    fig_crop: no
    fig_height: 8
    fig_width: 6
    highlight: haddock
    pandoc_args: -Fpandoc-crossref
 html_document:
  df_print: paged
 word_document:
  reference_docx: Style and bibliography/templatePaper.docx
  pandoc_args: -Fpandoc-crossref
 indent: true  
always_allow_html: yes
link-citations: true
csl: Style and bibliography/journal-of-clinical-epidemiology.csl
sansfont : GFS Neohellenic
bibliography: Style and bibliography/bibliography2.bib
---




# Abstract

## Introduction

Individual participant data (IPD) meta-analysis (MA) offer great opportunities, such as to simultaneously investigate effect modification while also modelling for potential non-linear association between the outcome and the effect modifier. Several approaches have been proposed such as fractional polynomials, meta-STEPP and splines. 

## Objective

Our objective is to compare properties and precision of the aforementioned approaches to investigate effect modification in IPD-MA.  

## Methods

To that goal we first describe the aforementioned methods. Subsequently, we conduct a simulation study covering 3 distinct scenarios. All scenarios consist of 5 studies with 200 participants each and equal treatment allocation reflecting the design of a randomised clinical trial. In the first scenario we introduced heterogeneity but the domain of the continuous effect modifier was the same across the studies. In the second scenario we introduced heterogeneity and the the domain of the continuous effect modifier was the different across the studies, while in the third scenario we added ecological bias.


## Results


## Conclusions



\newpage

# Introduction 


Individual participant data (IPD) meta-analysis (MA) is well established as the gold standard to synthesize evidence from multiple studies [@Riley_2010a ; @Riley_2010b]. IPD-MA offers great opportunities and showed great increase over the last decades [@Simmonds_2015]. Two opportunities that can be addressed in IPD-MA is the investigation of effect modification and modelling non-linear associations with the outcome. Estimating the real underlying functional shape between the outcome and a continuous variable is an important task, as failing to do so may lead to biased results and subsequently biased conclusions. Therefore, a plethora of modelling approaches have been proposed such as fractional polynomials, splines and sliding window techniques. Most of these approaches have been initially developed in a single studies and extended in multi-level schemes to account for the within study clustering of the participants. The aforementioned approaches can be classified in two categories. Fractional polynomials is a **global** method, while splines and sliding windows approaches are  **fragmented** methods. 

One of the first attempts to extent linear models to account non-linearities was polynomial regression approach. Hereby, powers of the continuous variable higher than one (linear) are generated and regressed with the outcome. Different degree polynomials are typically compared using tests such as likelihood ratio and Wald test or criteria such as AIC and BIC. Fractional polynomials [@Royston_1994 ; @Royston_2004] use the same approach as polynomial regression, but the powers that can be used come from a specific set $S: [-2; -1; -0:5; 0; 0:5; 1; 2; 3]$. Note that FPs introduce also negative powers, which offers great modeling capability. In our manuscript, we will not adress polynomial regression, as we believe that they are covered by fractional polynomials due to their similarity.

Splines are based on piece-wise polynomials. Although, a wide variety of methods has has been developed splines are generally considered semi-parametric. Nevertheless, some approaches tend to be more parametrica than others. As the term piece-wise implies the independent variables are splitted into sub-domains. The cut points for these splits are often called knots and the domains within each knot intervals. Note that simply fitting a polynomial within two adjacent interval, would produce discontinuous fitted lines. Therefore, splines are constrained to be continuous and in most approaches smooth over the knots. Splines can be classified in two categories **regression splines** and **penalised splines**. The most commonly used **regression splines** are restricted splines [cit] and B-splines [@de_Boor_1978 ; @Dierckx_1993]. On the other hand, the most commonly used **penalised splines** are smoothing splines [@Best_1994] and p-splines [@Eilers_1996].  

Sliding window - often called moving average or moving regression- are non-parametric approaches, as they make no distributional assumptions.  As the term sliding window implies, hereby, we focus in small subsets of data starting from the lowest value of the continuous variable and gradually reaching the highest. These small subsets are often called windows and the distance between the two consequent windows is called sliding step. The most common of sliding window approaches are Locally Weighted Scatterplot Smoothing (lowess) and Subpopulation Treatment Effect Pattern Plot (STEPP)[@Yip_2016]. 

All aforementioned modelling approaches have been also extended to meta-analysis. In general IPD-MA may be applied either in one-stage or two-stage. In two-stage IPD-MA, we may apply per study a statistical model of choice and then extract either 1) the estimated coefficients along with their standard errors or 2) their fitted lines along with their 95% confidence bands. Subsequently, we pool them with multivariate meta-analysis [@Berkeley_1996] or point-wise meta-analysis [@Sauerbrei_2011]. Apparently, methods that don't provide coefficients can not use this multi-variate meta-analysis. Furthermore, another limitation for this approach is that it may be applied only whenever the domain of the continuous variable is approximately common between studies. On the other hand, point-wise meta-analysis can be applied in both cases. Nevertheless, in scenarios where the domain of the independent variable is different point-wise meta-analysis may provide jagged fitted lines and confidence intervals. On the other hand, in one-stage meta-analysis a typically a mixed-effects model is applied to account for within study clustering of the participants. This way we assume that the coefficients and/or the fitted lines come from a higher distribution and they are different across studies due to randomness. 

Little is known about the properties of the aforementioned techniques. To address that, we perform a simulation study with continuous response in three different scenarios that reflect multi-level structures typically encountered in practise. As the performance of each method is highly dependent on the simulated functional shape we do not expect to find a single technique that outperforms all other in every case. Instead, our goal is to provide guidance on choosing the approach that fits best a given occasion. 
Our manuscript is organised as follows. In section 2 we describe the simulated scenarios and explain the IPD design and the performance measures used to . In section 3, we describe the aforementioned approaches and in section 4 we provide their results. Section 5 contains discussion and our conclusions.


# 2. IPD simulation 

## 2.1 

We describe three distinct scenarios commonly present in research practise. All scenarios consist of 5 studies with 200 participants each and equal treatment allocation reflecting the design of a randomised clinical trial.  The functional shape resembles a U-shaped association 






In the first scenario we introduce heterogeneity but the domain of the continuous effect modifier was the same across the studies. 








In the second scenario we introduced heterogeneity and the the domain of the continuous effect modifier was the different across the studies, while in the third scenario we added ecological bias. 









## Perfomance measurement

We calculated the mean prediction error of our approaches and 



# 3. Methods

## Fractional Polynomials

Royston and Altman [@Royston_1994] proposed a multi-variable fractional polynomial procedure (MFP) in order to detect the best fitting fractional polynomial including also interactions [@Royston_2004]  between binary variables such as treatments and continuous co-variables. In a subsequent article, Sauerbrei and Royston [@Sauerbrei_2011] extended fractional polynomials for IPD-MA, proposing a two-stage approach. 


Their suggested algorithm is as follows:

* 
* A fractional polynomial per trial is applied 






* Method 1: Overall FP
* Method 2: Studywise FP2
* Method 3: Studywise selected FP







First an appropriate statistical model is fitted per trial and either the estimated coefficients with their standard errors or the treatment effect functions with their 95% confidence intervals are extracted. On a second stage, these estimates are pooled using either multivariate or point-wise meta-analysis respectively. Nevertheless,their two-stage approach may be prone to power loss when IPD-set with limited observations are included and the outcome is binary [@Debray_2015]  or when the means of the continuous effect modifier is highly heterogeneous over the trials [@Simmonds_2007]. Furthermore, both the trial and error approach and the fractional polynomial approach rely on statistical tests with arbitrary $\alpha$ significance levels. Further, they estimate global functions which may not fit well on the boundaries of a continuous effect modifier. For instance, using the previous example, the regression model for BMI and mortality may on average fit well, using regression models with quadratic terms, but the fit may not be adequate for extreme cases such as underweight (BMI <18.5) and severely obese (BMI>40) participants. Splitting the BMI into 3 intervals [<18.5 , 18.5-40 , 40+] and fitting a model within each interval could provide a better fit, but the resulting piece-wise functional shapes will probably be discontinuous on the knots (18.5, 40). Therefore, piece-wise approaches are usually combined with smoothing techniques in order to result in continuous functional shapes.



# 4. Results

# 5. Discussion and conclusions




#

\newpage
# References













